# Generated by Django 4.2.6 on 2023-12-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
