# Generated by Django 4.2.6 on 2023-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
