# Generated by Django 4.2.6 on 2023-12-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_profile_savings_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
