# Generated by Django 4.2.6 on 2023-12-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_rename_photo_url_profile_name_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
