# Generated by Django 4.2.6 on 2023-12-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
