FROM python:3.9-slim

WORKDIR /app

RUN useradd -ms /bin/bash ryanzola

USER 0
RUN apt-get update && apt upgrade -y && apt-get install -y wait-for-it dos2unix

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . /app/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY --chown=ryanzola . .
COPY wsgi-entrypoint.sh .
RUN dos2unix migrate-script.sh
COPY --chown=ryanzola docker-start.sh .
RUN chmod 777 /app migrate-script.sh docker-start.sh

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

USER ryanzola