# Generated by Django 4.2.6 on 2024-08-08 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.town')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='queued', max_length=50)),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('items', models.TextField(default='[]')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tip', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.street'),
        ),
    ]
