# Generated by Django 4.2.6 on 2024-07-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_to_complete',
            new_name='date_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='date_placed',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='queued', max_length=50),
        ),
    ]
