# Generated by Django 4.2.6 on 2025-10-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_gamesession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='order_games_user_id_73bfc7_idx',
            old_name='order_games_user_id_0a1f1c_idx',
        ),
    ]
